name: Code Checks
on:
  push: {}
jobs:
  test:
    name: Build, check source and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - 1.11
        otp:
          - 23.2
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: mailer 
          POSTGRES_PASSWORD: mailer 
          POSTGRES_DB: mailer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
      - name: Compile
        run: mix compile
      - name: Code quality
        run: mix quality
      - name: Test with coverage
        run: mix coveralls
        env:
          MIX_ENV: test
          DB_USER: mailer 
          DB_PASSWORD: mailer 
          DB_NAME: mailer 
      - name: Retrieve Cached PLTs
        uses: actions/cache@v2
        id: plt-cache
        with:
          path: |
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - name: Generate PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt
      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
